const aliasEquipos = {
    "manchester city": "man city",
    "manchester united": "man united",
    "newcastle united": "newcastle",
    'Kaiserslautern': 'Kaiserslautern',
    'Preußen Muenster': 'SC Preussen 06 Munster',
    'Equidad Seguros': 'Equidad',
    'Atletico Nacional S.': 'Atlético Nacional',
    'Club Deportivo Junior':'Junior FC',
    'Aguilas Doradas Rionegro +++':'Águilas Doradas',
    'Real Betis':'Real Betis',
    'Athletic Bilbao':'Athletic Club',
    'AC Milán':'AC Milan',
    'Inter':'Inter Milán',
    'Eintracht Frankfurt':'Eintracht Frankfurt',
    'VfL Wolfsburg':'Wolfsburgo',
    'TSG Hoffenheim':'Hoffenheim',
    'SC Paderborn 07':'SC Paderborn',
    'Greuther Fürth':'Greuther Furth',
    'Toulouse':'Toulouse FC',
    'Niza':'OGC Niza',
    'Le Havre':'Le Havre AC',
    'Reims':'Stade Reims',
    'Nantes':'FC Nantes',
    'Estrasburgo':'RC Strasbourg Alsace',
    'Rennes':'Stade Rennais',
    'Rot-Weiss Essen':'RW Essen',
    'SpVgg Unterhaching':'Unterhaching',
    'VfL Osnabrück':'Osnabruck',
    'Lanús':'Atlético Lanus',
    'Sarmiento':'CA Sarmiento',
    'San Lorenzo':'CA San Lorenzo de Almagro',
    'Brisbane Roar FC (F)':'Brisbane Roar',
    'Wellington Phoenix FC (F)':'Wellington Phoenix FC',
    'LASK Linz':'LASK',
    'Red Bull Salzburg':'RB Salzburgo',
    'Nova Iguaçu-RJ':'Nova Iguacu RJ',
    'Figueirense-SC':'Figueirense SC',
    'Caravaggio':'Caravaggio FC SC',
    'Hercílio Luz-':'Hercilio Luz FC SC',
    'Marcílio Dias-':'CN Marcilio Dias SC',
    'Concordia-':'Concordia AC SC',
    'Caxias-RS':'SER Caxias do Sul',
    'Juventude-RS':'Juventude',
    'Guarany-':'Guarany de Bage',
    'Pelotas':'EC Pelotas RS',
    'ABECAT Ouvidorense':'Abecat Ouvidorense GO',
    'Anápolis-':'Anapolis FC GO',
    'Vila Nova-':'Vila Nova FC GO',
    'Goias-':'Goiás GO',
    'Democrata GV-':'EC Democrata GV MG',
    'Pouso Alegre-':'Pouso Alegre FC',
    'Itabirito FC-':'Itabirito FC MG',
    'Sport Club Aymores':'SC Aymores MG',
    'Cruzeiro-MG':'Cruzeiro',
    'Uberlândia-MG':'Uberlandia MG',
    'Joseense-':'Independente Futebol Sao Joseense PR',
    'Londrina-':'Londrina EC PR',
    'Clube Andraus Brasil-PR':'Clube Andraus Brasil PR',
    'Athletico Paranaense-PR':'Atlético Paranaense',
    'Santos-SP':'Santos',
    'São Paulo-SP':'Sao Paulo FC SP',
    'Velo Clube-SP':'AE Velo Clube SP',
    'Mirassol-SP':'Mirassol FC SP',
    'Agua Santa-':'EC Agua Santa SP',
    'Ponte Preta-':'Ponte Preta SP',
    'Oeste-':'Oeste FC',
    'Gremio Prudente-':'Prudente SP',
    'Taubate-':'EC Taubate',
    'Bento-':'EC Sao Bento SP',
    'de Piracicaba-':'EC Xv de Novembro Piracicaba SP',
    'Santo Andre-':'EC Santo Andre SP',
    'Botafogo-':'Botafogo FR RJ',
    'Flamengo-':'CR Flamengo RJ',
    'Francs Borains':'Royal Francs Borains',
    'RAAL La Louvière':'Raal La Louviere',
    'Zulte Waregem':'SV Zulte Waregem',
    'Genk Sub':'Jong Genk',
    'Beveren':'Waasland-Beveren',
    'Royal Antwerp FC':'Royal Antwerpen FC',
    'Club Brugge':'Club Brujas',
    'Sint-Truiden':'Sint-Truidense VV',
    'AA Gent':'KAA Gent',
    'Anderlecht':'RSC Anderlecht',
    'Kortrijk':'KV Kortrijk',
    'Westerlo':'KVC Westerlo',
    'Rangers de Talca':'CSD Rangers',
    'Cobreloa':'CD Cobreloa Calama',
    'Jaguares de Cordoba':'Jaguares FC',
    'Sporting San Jose FC':'Sporting FC',
    'Lokomotiva Zagreb':'NK Lokomotiva Zagreb',
    'Hajduk Split':'HNK Hajduk Split',
    'Ahly Cairo':'AL Ahly SC',
    'Future FC':'Modern Sport FC',
    'Fuerte San Francisco Morazan':'CD Fuerte San Francisco',
    'Rangers FC':'Rangers',
    'Ross County':'Ross County FC',
    '-Weiss Essen':'RW Essen',
    'Gimnasia de La Plata':'Gimnasia Y Esgrima La Plata',
    'Independiente':'CA Independiente',
    'Club Atletico Velez Sarsfield':'Vélez Sarsfield',
    'Instituto':'Instituto AC Córdoba',
    'Sampaio Correa':'Sampaio Correa FE RJ',
    'Bangu-':'Bangu RJ',
    'Caravaggio':'Caravaggio FC SC',
    'Internacional P. A.':'Internacional RS',
    'Avenida-':'EC Avenida RS',
    'Aris Limassol':'Aris FC Limassol',
    'Omonia Nicosia':'Omonia Nicosia',
    'Platense Zacatecoluca':'CD Platense Zacatecoluca',
    'Calavera CF Sub-':'Calavera CF',
    'Malaga Sub-':'Málaga CF',
    'Choco':'CD Choco',
    'Txantrea':'UDC Txantrea',
    'Athletic Club Bilbao sub':'Athletic Bilbao',
    'Val Minor Nigran':'ED Val Minor Nigran',
    'Celta Vigo':'RC Celta Vigo',
    'Rozas Sub-':'Las Rozas CF',
    'Alcorcon':'AD Alcorcon',
    'Eibar':'SD Eibar',
    'Granadilla Tenerife':'UD Costa Adeje Tenerife',
    'Real Union':'Real Unión Club',
    'Valencia Mestalla':'Valencia CF II',
    'San Sebastian de los Reyes':'UD SS de los Reyes',
    'Athletic Club Torrellano':'Athletic Torrellano',
    'Trival Valderas':'CF Trival Valderas Alcorcón',
    'Olympiakos Piraeus':'Olympiacos',
    'Aris Thessaloniki':'Aris Tesalónica',
    'PAOK Thessaloniki':'PAOK Salónica',
    'Panetolikos Agrinio':'Panaitolikos Agrinio',
    'Atromitos Athens':'Atromitos Athinon',
    'DVSC Debreceni':'Debreceni VSC',
    'Nyiregyhaza Spartacus':'Nyiregyhaza Spartacus FC',
    'Leones Negros UDG':'Leones Negros UDEG',
    'Coyotes de Tlaxcala':'Tlaxcala FC',
    'Sporting Lisboa':'Sporting CP',
    'Tanjong Pagar United':'Tanjong Pagar Utd FC',
    'Pathumthani United':'BG Pathum United FC',
    'Sekhukhune United FC Reserves':'Sekhukhune United',
    'Orlando Pirates Reserves':'Orlando Pirates',
    'Tanjong Pagar United':'Tanjong Pagar Utd FC',
    'Pathumthani United':'BG Pathum United FC',
    'Stellenbosch F.C. Reserves':'Stellenbosch FC',
    'Cape Town City Reserves':'Cape Town City FC',
    'Zuerich':'FC Zúrich',
    'Basilea':'FC Basel 1893',
    'Unyegucu Futbol Kulubu':'Unye Kadin SK',
    'Ankaraguecue':'MKE Ankaragucu',
    'Sakaryaspor A.S.':'Sakaryaspor',
    'Erokspor A.S.':'Esenler Erokspor',
    'Nacional de Montevideo':'Club Nacional de Football',
    '':'',
};


const normalizeText = (text) => {
    // text = text.toLowerCase().trim();
    text = text.trim();
    return aliasEquipos[text] || text;
};

module.exports = {normalizeText};